// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtAfigDsp_7ZG_ZDZO3WGbMoWDRzj9YwE',
    appId: '1:153326923968:web:827500e59f2036cedabd25',
    messagingSenderId: '153326923968',
    projectId: 'flutterinta',
    authDomain: 'flutterinta.firebaseapp.com',
    storageBucket: 'flutterinta.firebasestorage.app',
    measurementId: 'G-FMJL3LSVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPrA4Yk0eD4ntm1s3jIG3dHBGatQv7qOE',
    appId: '1:153326923968:android:4259bbe6547f3086dabd25',
    messagingSenderId: '153326923968',
    projectId: 'flutterinta',
    storageBucket: 'flutterinta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfk5yqRTPuz2lheidVx4fnqhp0U3-mVAA',
    appId: '1:153326923968:ios:580a49345f564ee9dabd25',
    messagingSenderId: '153326923968',
    projectId: 'flutterinta',
    storageBucket: 'flutterinta.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfk5yqRTPuz2lheidVx4fnqhp0U3-mVAA',
    appId: '1:153326923968:ios:580a49345f564ee9dabd25',
    messagingSenderId: '153326923968',
    projectId: 'flutterinta',
    storageBucket: 'flutterinta.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtAfigDsp_7ZG_ZDZO3WGbMoWDRzj9YwE',
    appId: '1:153326923968:web:fad7fa550576dcb6dabd25',
    messagingSenderId: '153326923968',
    projectId: 'flutterinta',
    authDomain: 'flutterinta.firebaseapp.com',
    storageBucket: 'flutterinta.firebasestorage.app',
    measurementId: 'G-1ZQ36NSTL7',
  );

}